### ISSUE TITLE
test_function_result not working for pipes in spark course

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#104] opened 2017-05-16 19:51 UTC
From pairing w/ @sumedh10 , test_function_result is commonly used in the dplyr course, in order to test each piece of a pipe. However this function seems to always fail in the spark course.

See this exercise for the guilty SCT:

https://github.com/datacamp/courses-intro-spark-r/blob/beta-testing-fixes-sp/chapter1.md#arranging-rows

**Comment by machow** [comment] 2017-05-16 19:52
For a dplyr case that's working, see

https://github.com/datacamp/courses-dplyr/blob/master/chapter5.Rmd#unite-and-conquer-using-group_by

cc @filipsch

**Comment by filipsch** [comment] 2018-04-17 12:36
I can no longer find the exercise. The SCT seems to have changed since the last time I checked. I am closing this as I have no way to reproduce this. @sumedh10 let me know if you still remember any of this and can provide a minimal example to reproduce. Thanks!

**Closed by filipsch** 2018-04-17 12:36 UTC
Labels: bug
